[phases.setup]
nixPkgs = ['nodejs-18_x', 'php81', 'php81Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci --only=production',
    'npm run build'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'