[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"
SESSION_DRIVER = "database"
CACHE_STORE = "database"
QUEUE_CONNECTION = "database"