services:
  - type: web
    name: pems
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm ci
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: نظام إدارة مصروفات الإنتاج الفني
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:oa1iAO5nLuw10KKYMwHvqZc2WNS3TUa0GPTgoEbYXXw=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-ap-southeast-2.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.yhaonlrrndhimhrrmgsd
      - key: DB_PASSWORD
        value: p7wM8FnnNuOZcURM
      - key: DB_SSLMODE
        value: require