services:
  - type: web
    name: pems
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: PEMS
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:E4RxCe2GSycdoxi3mp6fUa5QF2SHNvAlFAb2+Hdoisk=
      - key: APP_DEBUG
        value: false
      - key: APP_LOCALE
        value: ar
      - key: DB_CONNECTION
        value: sqlite
      - key: DEMO_MODE
        value: true
      - key: SEED_DEMO_DATA
        value: true